import Kiran from "@/../public/assets/home/trustees/Kiran.jpg";
import Rumjhum from "@/../public/assets/home/trustees/Rumjhum.jpg";
import kiranImg from "@/../public/assets/home/trustees/kiranImg.png";
import rumjhumImg from "@/../public/assets/home/trustees/rumjhumImg.png";
import vinayakImg from "@/../public/assets/home/trustees/vinayakImg.png";



import Arun from "@/../public/assets/home/advisory/Arun.jpg";
import ArunNanda from "@/../public/assets/home/advisory/ArunNanda.jpg";
import AshishDhawan from "@/../public/assets/home/advisory/AshishDhawan.jpg";
import CyrilShroff from "@/../public/assets/home/advisory/CyrilShroff.png";
import DKSen from "@/../public/assets/home/advisory/DKSen.jpg";
import JanmejayaKSinha from "@/../public/assets/home/advisory/JanmejayaKSinha.jpg";
import GeetanjaliKirloskar from "@/../public/assets/home/advisory/GeetanjaliKirloskar.jpg";
import HemendraMKothari from "@/../public/assets/home/advisory/HemendraMKothari.jpg";
import jagan from "@/../public/assets/home/advisory/jagan.jpg";
import khurshed from "@/../public/assets/home/advisory/khurshed.jpg";
import NarotamSekhsaria from "@/../public/assets/home/advisory/NarotamSekhsaria.jpg";
import ProfessorGRaghuram from "@/../public/assets/home/advisory/ProfessorGRaghuram.jpg";
import NasserMunjee from "@/../public/assets/home/advisory/NasserMunjee.jpg";
import RajnishKumar from "@/../public/assets/home/advisory/RajnishKumar.jpg";
import SameerGupta from "@/../public/assets/home/advisory/SameerGupta.jpg";
import SNSubrahmanyan from "@/../public/assets/home/advisory/SNSubrahmanyan.jpg";
import SunilMathur from "@/../public/assets/home/advisory/SunilMathur.jpg";
import DilipCherian from "@/../public/assets/home/advisory/DilipCherian.jpg";
import ManojKSingh from "@/../public/assets/home/advisory/ManojKSingh.jpg";
import VishalKampani from "@/../public/assets/home/advisory/VishalKampani.png";

import AkhileshTilotia from "@/../public/assets/home/fellows/AkhileshTilotia.jpg";
import rajajiMeshram from "@/../public/assets/home/fellows/rajajiMeshram.png";
import rajivRanjanMishra from "@/../public/assets/home/fellows/rajivRanjanMishra.jpg";
import rasikaAthawale from "@/../public/assets/home/fellows/rasikaAthawale.jpg";
import SoumyaKantiGhosh from "@/../public/assets/home/fellows/SoumyaKantiGhosh.jpg";
import supratimSarkar from "@/../public/assets/home/fellows/supratimSarkar.jpg";

import MutumChaobisana from "@/../public/assets/home/team/MutumChaobisana.png";
import KavereeBamzai from "@/../public/assets/home/team/KavereeBamzai.png";
import LawrenceCardoza from "@/../public/assets/home/team/LawrenceCardoza.jpg";
import PriyankaBains from "@/../public/assets/home/team/PriyankaBains.jpg";
import RumjhumChatterjee from "@/../public/assets/home/team/RumjhumChatterjee.jpg";
import Vinayak from "@/../public/assets/home/team/Vinayak.jpg";
import VrindaSingh from "@/../public/assets/home/team/VrindaSingh.png";



import { StaticImageData } from "next/image";

export type CardData = {
  image: StaticImageData;
  title: string;
  desig: string;
  link?: string;
  popupImg:string;
  popupdesc?:string;
};

export const trustee = [
  {
    image: Vinayak,
    title: "Vinayak Chatterjee",
    desig: "Founder & Managing Trustee",
    popupImg:vinayakImg.src,

    popupdesc:"Born in 1959, Vinayak Chatterjee graduated in Economics (Hons.) from St. Stephen's College, Delhi University (1976-1979) and did his MBA from the Indian Institute of Management, Ahmedabad (1979 – 1981). He co-founded Feedback Infra Pvt. Ltd. in 1990 and served as its Chairman from 1990 to 2021. Since stepping down from active management, he now devotes his time and energy to Infrastructure Policy and Advocacy; as well as to nurturing educational institutions.He has often been called upon to play a strategic advisory role to leading domestic and international corporates, the Government of India, various Ministries dealing with infrastructure, as well as multilateral and bilateral institutions in the areas of infrastructure policy, planning, and implementation. He is one of the leading proponents of the Public-Private Partnership (PPP) model for developing India’s infrastructure. His more recent engagements with the Government of India relate to being a Member of the Committee on Setting up a Development Finance Institution (DFI), and a member of the Consultative Group on PPPs at NITI Aayog.In 1998, the World Economic Forum at Davos recognized him as one of the 100 Global Leaders of Tomorrow. In 2011, the Indian Institute of Management, Ahmedabad conferred on him the “Distinguished Alumnus Award”. He is currently the Chairman of the Confederation of Indian Industry’s (CII) “National Council on Infrastructure” and has chaired various Infrastructure and Economic Committees at the national level of CII since 2001. He is on the Board of Directors of ACC Limited, Apollo Hospitals Enterprise Limited, KEC International Limited, and L&T Infotech Limited; and is a member of the Advisory Board of JCB India. He serves as the Chairman of the Board of Governors of Indian Institute of Technology, Dharwad, and on the Boards of Indian Institute of Management, Sirmaur and the National Rail and Transportation Institute, Vadodara.He is a well-read columnist and writes a monthly column on infrastructure for Business Standard called “INFRATALK”. He has also authored a book titled <span class='font-semibold teaxt-black'>“Getting it Right – India’s Unfolding Infrastructure Agenda”</span> published in 2011."
  },
  {
    image: Rumjhum,
    title: "Rumjhum Chatterjee",
    desig: "Co-Founder & Managing Trustee",
    link: "https://www.linkedin.com/in/rumjhum-chatterjee-396041268/",
    popupImg:rumjhumImg.src,
    
    popupdesc:"Rumjhum Chatterjee co-founded the Feedback Infra Group. Following a successful tenure, she recently stepped down from her role as Group Managing Director and Head — Human Capital within the organization.<br/>She is currently the Chairperson of the Feedback Foundation Charitable Trust. The Trust is deeply involved in rural and urban sanitation issues, including solid waste management. It has successfully implemented several projects across the country through community engagement. Rumjhum pioneered the practice of community-led interventions for Resettlement and Rehabilitation (R&R) post land acquisition for infrastructure projects. Her paper on “Sustainable Rehabilitation Interventions through Community Engagement” was published in the India Infrastructure Report 2009, issued by the 3iNetwork.<br/>A leading practitioner of the management of human capital in the infrastructure sector, she was recognized as one of the 20 Most Talented HR Leaders in India by the World HRD Congress in 2013. She plays an active role in the Confederation of Indian Industry (CII). She was the first woman Chairperson for CII Northern Regional Council (2016-17). She has a deep interest in women empowerment. She was also the Chairperson of CII’s Women Exemplar Program (2015-17) and has been part of the Jury of the Selection Committee of the same program since its inception in 2005. She served as the Chair of the CII National Women’s Empowerment Committee for several years. Her devotion to the cause of women empowerment  has led her to represent the industry's perspective on this critical issue before Parliamentarians in India. She also participated in a closed-door interaction to discuss the same with the Prime Minister of Japan, Mr. Shinzo Abe, during his visit to India in January 2014.Currently, she Co-Chairs CII’s National Committee on CSR. She has served as an Independent Director on the Board of Blue Star Ltd. and currently serves on the Board of Somany Ceramics Ltd. and C&S Electric Ltd. (a subsidiary of Siemens India Ltd.). She is the Vice Chairperson and a member of the Governing Body of HelpAge India — India’s largest not-for-profit organisation dedicated to the welfare of the aged. She is also a Trustee of HDFC Schools. Rumjhum is educated in Psychology from Calcutta University."
  },

  {
    image: Kiran,
    title: "Kiran Karnik",
    desig: "Trustee",
    popupImg:kiranImg.src,
    
    popupdesc:"Few people in India can claim to have as brilliant a career in public service and in the corporate world as Kiran Karnik. One of the architects of the communications industry in India, he has always been at the cutting edge of technology, whether it was working with the late great Vikram Sarabhai to set up the Satellite Instructional Television Experiment or laying the foundations of Discovery Channel and Animal Planet in India. He is the person governments invariably turn to in a crisis, whether it was managing NASSCOM after the sudden passing on of Dewang Mehta or heading the Satyam Computer Services board after it was disbanded for irregularities. Mr. Karnik's ability to master the many transitions in technology and mentor those who manage it have made him an invaluable national asset. Mr Karnik has been President of the India Habitat Centre as well as Chairman IIITD and is currently Chair of HelpAge India. He has also been conferred the prestigious Padma Shri award. We are honoured that he has agreed to guide us as a Trustee."
  },
];

export const advisory = [
  {
    image: NasserMunjee,
    title: "Nasser Munjee",
    desig: "Member, Council of Advisors",
    link: "https://www.linkedin.com/in/nasser-munjee-8aaa5316/",
    popupImg:vinayakImg.src,
   
    popupdesc:"Born in 1952 and educated primarily in the UK (Cambridge, and London School of Economics) and the US (University of Chicago), his entire career has spanned the creation of financial institutions in India and in addressing the problems of development in an emerging economy. He was involved in the creation of the first mortgage company in India - the Housing Development Finance Corporation (HDFC) - with which he was associated for twenty years, rising to be its Executive Director. At the request of the Chairman of HDFC, he created the Infrastructure Development Finance Company in joint partnership with government and domestic and international institutions, which company he ran as Managing Director and CEO for seven years. He is presently on the Board of ten public companies in India including Cummins India Limited, Ambuja Cements Limited (Holcim Group), Tata Motor Finance Ltd (Group Chairman), The Indian Hotels Company Limited, and is also on several international Boards such as Jaguar Land Rover Plc, UK Greenko, Mauritius, Adsum Capital Ltd, Dubai, Advisory Group of the City of London, and Executive Committee of the World Islamic Economic Forum. He is involved with several other institutions as Chairman, including Aga Khan Foundation (India), Aga Khan Rural Support Programme (India), Global Infrasys Limited, Advisory Board of the South Asian Centre, London School of Economics, Bombay City Policy and Research Foundation (Bombay Chamber of Commerce). Other institutions in which he has served as a Board member or Trustee include Welham Boys School, Dehradun, Life Trustee - Indian Institute for Human Settlements (Member of the Board), Charles Correa Urban Foundation, Goa, Currimbhoy Orphanage, Advisory Board of the Schulich School of Management, University of Toronto, CanCare Trust, Miracle Feet, and Sommerville College, Oxford India Centre. He has consulted with the Asian Development Bank, The World Bank, the UNCDF (United Nations Capital Development Fund) and the UN (Habitat) in the field of housing finance in Sri Lanka, Bhutan, Ethiopia, Thailand and Indonesia."
  },
  {
    image: HemendraMKothari,
    title: "Hemendra M. Kothari",
    desig: "Member, Council of Advisors",
    popupImg:vinayakImg.src,
  
    popupdesc:"Mr. Hemendra Kothari represents the fourth generation of a family of prominent stockbrokers and is the ex-President of the Bombay Stock Exchange. He has over 50 years of experience in the financial services industry and is currently the Chairman of DSP Investment Managers Private Limited, one of the leading asset management companies in India, which was in a decade-long joint venture with BlackRock. He also served as Chairman of DSP Merrill Lynch, a joint venture with Merrill Lynch, till his retirement in 2009. He is a Member of the Governing Council of the National Investment and Infrastructure Fund (NIIF), which was created by the Government of India, to maximize economic impact through infrastructure development. He has also served as a member on various boards & committees viz The National Institute of Securities Market (NISM), set up by the Securities and Exchange Board of India (SEBI), the Corporatisation & Demutualization of Stock Exchanges Committee, the Infrastructure Financing, Department of Economic Affairs (Infrastructure), Ministry of Finance and the Standing Committee on Money Markets, Reserve Bank of India. He presently serves on the Investment Advisory Committee of the Army Group Insurance Fund. He was a Member of the Indo-UK Roundtable which was established by The British Foreign & Commonwealth Office and The Ministry of External Affairs, Government of India. He is presently a Member of the India –UK Financial Partnership (IUKFP). Mr. Kothari is the Founder, Chairman & Managing Trustee of the Wildlife Conservation Trust (WCT), a non-religious and non-political, not-for-profit Trust that endeavours to strengthen the protection of forest ecosystems and mitigate climate change. He is also one of the largest individual donors in wildlife and environment conservation, in India. He is a Member of the State Board for Wildlife of Rajasthan under the Chairmanship of the Chief Minister. He also served as a Member of the State Board of Maharashtra. He serves as the India Chairman of The Nature Conservancy (TNC), the largest environmental organization in the world. He has served as a Member of The Energy and Resources Institute (TERI) Governing Council. He founded The Hemendra Kothari Foundation (HKF), a philanthropic organization which assists other NGOs, particularly in the areas of education, healthcare, art, culture, heritage and sports."
  },
  {
    image: JanmejayaKSinha,
    title: "Janmejaya K. Sinha",
    desig: "Member, Council of Advisors",
    popupImg:vinayakImg.src,
    
    popupdesc:"Dr Janmejaya Sinha is Chairman of BCG's India Practice and also a BCG Fellow doing research on the subject of Family Businesses. He is a member of The Boston Consulting Group’s Henderson Institute Innovation Sounding Board, which is dedicated to supporting, inspiring, and guiding upstream innovation at BCG. Previously served as Chairman of the Asia-Pacific region between 2009 – 2018 and as a member of the firm's Executive Committee between 2006 – 2018. He has deep expertise in managing conflict in family-owned businesses. He has worked extensively with clients across the world over a range of issues encompassing large-scale organization transformation, strategy, governance, family business issues and operations turnaround. He has been a member of various committees set up by the Government of India, Reserve Bank of India (RBI), Indian Banks' Association (IBA), and chairs the Confederation of Indian Industry's Committee on Financial Inclusion and Fintech. He was a member of the Committee of Chief Ministers on the adoption of Digital Payments. He writes extensively in the press and is a regular speaker at the WEF, CII, IBA, FICCI, RBI and other media events. He is a co-author of the book titled “Your Strategy Needs a Strategy” published by Harvard Business Review Press and has co-edited the book titled 'Own The Future' published by Wiley. In 2010, the Consulting Magazine named him one of the Top 25 most influential consultants in the world. Prior to joining The Boston Consulting Group, he worked with the Reserve Bank of India for several years across different departments. He has also worked briefly for the World Bank. Dr. Sinha has a Ph.D from the Woodrow Wilson School of Public and International Affairs, Princeton University, US, a BA and an MA in Economics from Clare College, Cambridge University, UK and a BA and an MA in History from St Stephen’s College, Delhi University, India."
  },
  {
    image: NarotamSekhsaria,
    title: "Narotam Sekhsaria",
    desig: "Member, Council of Advisors",
    popupImg:vinayakImg.src,
    
    popupdesc:"Narotam Sekhsaria, Chairman, Ambuja Cements Ltd, and Chairman, ACC Ltd, is a doyen of the Indian cement industry and one of the most respected business personalities in India. He introduced new standards in manufacturing, management, marketing efficiency and corporate social responsibility to an industry he has helped transform. A first-generation industrialist, Mr Sekhsaria did his Bachelor’s in Chemical Engineering with honours and distinction from the University of Bombay. He was the principal founder-promoter of Ambuja Cement, and the Chief Executive & Managing Director of the Company since its inception in April 1983 till January 2006. He is the present non-executive Chairman of the Company. He built Ambuja Cement into the most efficient and profitable cement Company in India. He also re-defined the industry practices by turning cement from a commodity into a brand, bringing cement plants closer to cement markets and linking plants to lucrative coastal markets by setting up ports and a fleet of bulk cement ships for the first time in India. During his tenure as Managing Director from the inception till 2006, the Company grew from 0.7 million tonne capacity to 22 million tonnes, from one location footprint to a pan-India Company which set the benchmark for the cement industry across every significant business parameter. In the year 1999, Ambuja Cement made a strategic investment in ACC, India's oldest and most prestigious cement company by acquiring about 14.5% stake. Mr. Sekhsaria was appointed Vice-chairman of the Company. Under his leadership, ACC entered a new growth trajectory and has achieved significant improvements in the areas of project management, logistics and overall cost-competitiveness. Mr. Sekhsaria is the non-executive Chairman of the Company from 2006. He currently holds Board positions in Narotam Sekhsaria Foundation and Ambuja Cement Foundation as Chairman, is a Board Member in the Governing Council of the Indian Institute of Crafts & Design, Jaipur, and is Director of the Ambuja Educational Institute. Previously he has served as a Trustee on the Board of UTI (1993-2001), as the Vice Chairman of GRUH Finance Ltd, as a co-investment of Ambuja Cement with HDFC, and was also on the Board of Governors of the Indian Institute of Technology (IIT) Kharagpur."
  },
  {
    image: RajnishKumar,
    title: "Rajnish Kumar",
    desig: "Member, Council of Advisors",
    popupImg:vinayakImg.src,
   
    popupdesc:"Mr Rajnish Kumar is the former Chairman of State Bank of India. He completed his 3 year-term as Chairman in October 2020. He is credited with steering the bank successfully through very challenging times. During his tenure, SBI developed YONO, a digital platform, which has established the bank as a global leader in the adoption of technology and innovation. Mr Kumar is a career banker with nearly 4 decades of service with the State Bank of India. His expertise in corporate credit and project finance is well recognised. He served the bank in various capacities across the country including in the North-East as Chief General Manager. He successfully managed the UK operations of the Bank immediately after the crisis caused by the collapse of Lehman Brothers. Earlier he worked as Vice President (Credit) at Toronto. Mr Kumar was also the Chairman of SBI’s subsidiaries, the important ones being, SBI Life Insurance Company Limited, SBI Foundation, SBI Capital Markets Limited, and SBI Cards & Payments Services Limited. He also served as Director on the boards of various organizations, viz. Export-Import Bank of India, Institute of Banking Personnel Selection, National Institute of Bank Management, Pune, Indian Banks’ Association, Khadi & Village Industries Commission, Indian Institute of Banking & Finance, among others. He is currently serving as an independent director on the Boards of many prestigious companies like HSBC, Asia Pacific and L&T Infotech. He is also Non-Executive Chairman of Resilient Innovations Pvt Ltd. (BharatPe), one of the fastest growing Fintech in the country, and independent director on the Board of Lighthouse Communities Foundation. Mr Kumar is also an advisor to Kotaik Investment Advisors Ltd and Barings Private Equity Asia Ltd, apart from being Member, the Board of Governors, Management Development Institute, Gurugram. Born in January 1958, Mr Kumar has done M.Sc. in Physics from Meerut University and is also a Certified Associate of the Indian Institute of Bankers (CAIIB). Mr Kumar is an avid traveller and has visited several countries. He is passionate about sports and his favourite sport is badminton."
  },
  {
    image: ProfessorGRaghuram,
    title: "Professor G. Raghuram",
    desig: "Member, Council of Advisors",
    popupImg:vinayakImg.src,

    popupdesc:"Professor Raghuram is Principal Academic Advisor and Distinguished Visiting Faculty at the National Rail and Transportation Institute, a university promoted by the Indian Ministry of Railways. He is Professor (Emeritus) at the Gujarat Maritime University, a university promoted by the Gujarat Maritime Board. He has been Director, IIM Bangalore, from February 2017 to July 2020. Earlier, he was Professor and Chairperson of the Public Systems Group at IIMA. He has been Dean (Faculty), IIMA, Vice-Chancellor of the Indian Maritime University and held the Indian Railways Chair Professor at IIMA. Prof Raghuram received a PhD from Northwestern University, USA (1984); a Post Graduate Diploma in Management from IIM, Ahmedabad (1978); and a BTech from IIT, Madras (1976). He specializes in infrastructure and transport systems, and logistics and supply chain management. He conducts research on the railway, port, shipping, aviation, and road sectors. He has published over 35 refereed papers in journals and written over 160 case studies. He has published six co-authored books. His expertise is applied Operations Research and Management modelling in network-oriented firms including railroads and logistics, and Public Policy in the context of PPPs in transport infrastructure. He is on the Board of Directors of several companies in the fields of infrastructure and logistics, educational institutions, and Foundations working in the domain of Logistics and Transportation. He has teaching experience at universities in India, the USA, Canada, Yugoslavia, Singapore, Tanzania, UAE, and Japan. He was a member of the Global Future Council on Mobility of the World Economic Forum during 2013-17. He was awarded the ‘Lifetime Achievement Award’ for Transport Excellence, by Mahindra and Mahindra, supported by the Ministry of Road Transport and Highways in 2018, the ‘MC Puri Memorial Award’ for contribution to Operational Research in India in 2016, and ‘The Lifetime Achievement Award’ for contribution to Logistics and Infrastructure by EXIM News in 2014. He has offered consultancy services to over 100 organizations including multilateral agencies. He has been part of various government policy-making and advisory committees for the Ministries of Civil Aviation, Consumer Affairs and Public Distribution, Railways, Road Transport and Highways, and Shipping. He has played roles in the Cabinet Secretariat, Comptroller and Auditor General, the Planning Commission and various State Governments."
  },
  {
    image: ManojKSingh,
    title: "Manoj K. Singh",
    desig: "Member, Council of Advisors",
    link: "https://www.linkedin.com/in/manoj-k-singh-72817a9/",
    popupImg:vinayakImg.src,
    popupdesc:"Mr Manoj K Singh of S&A Law Offices, New Delhi India, is one of India’s most reputable lawyers specialising in commercial disputes and advisory, with a keen focus on the domain of Infrastructure. His practice area encompasses commercial litigation and arbitration, both domestic and international, white-collar crime, bankruptcy law, company law, international trade law, banking & debt recovery laws, securities law and taxation. He advises clients in all aspects related to the functioning of infrastructure projects, foreign investment in India, offshore commercial borrowings, cross-border taxation, project financing, anti-dumping, energy and natural resources. His expertise also includes advising clients on commercial dispute strategies, troubleshooting advisory, and general corporate advisory. Mr. Singh is a very experienced and skilled lawyer with a wide reputation for arbitration and commercial litigation. Mr. Singh currently represents various Fortune 500 companies and large business houses. He is admired for his out-of-the-box, goal-oriented thinking and for achieving results in complex legal cases. He has about two decades of rich experience on various legal issues, during which he has appeared and argued matters before the Hon’ble Supreme Court of India, all High Courts in India, various Tribunals and ad-hoc and institutional arbitrations, both domestic and international. Mr. Singh has also acted on behalf of various government authorities including the Government of Madhya Pradesh, New Delhi Municipal Corporation, South Delhi Municipal Corporation, Delhi Transco Ltd., Delhi Power Company Limited, Indian Oil Corporation, Government of Rajasthan, Container Corporation of India, IRCON International Limited, The Shipping Corporation of India Ltd., Solar Corporation of India, IIT Jodhpur, Rail Development Authority of India, Delhi Development Authority, Delhi Co-operative Housing Finance Corporation Ltd., Defence Research and Development Organization, National Research Development Council, Technology Information, Forecasting and Assessment Council, The Institute of Cost Accountants of India, and Centre for E-Governance. Apart from having been a prolific columnist in his field, Mr. Singh has also authored the book titled ‘Infrastructure Arbitration – A Perspective’ which is a manifestation of his deep‐rooted knowledge of arbitration and commercial contracts, widely recognised as the most informative literature in the field."
  },

  {
    image: SunilMathur,
    title: "Sunil Mathur",
    desig: "Member, Council of Advisors",
    link: "https://www.linkedin.com/in/sunil-mathur/",
    popupImg:vinayakImg.src,
    popupdesc:"Mr Sunil Mathur has been the Managing Director and Chief Executive Officer of Siemens Limited, India and South Asia since 2014. He is currently a Member of the Global Leadership Team of Siemens; a Member of the Board of Siemens Healthcare Private Limited in India and Chairman of Siemens Gamesa Renewable Power Private Ltd in India. Prior to 2014, he was the Executive Director and Chief Financial Officer of Siemens Limited from 2008 responsible for Sri Lanka, Bangladesh, Nepal & Bhutan, during which stint he was a Member of the Global Finance Management Team. He has been with Siemens for over 30 years, holding several Senior Management positions in Germany, where he worked in the Power Generation Division and also as Chief Financial Officer of a Global Business Unit in the Industrial Automation Division of the Company. He has wide experience in integrating companies, creating Joint Ventures, M&A and turning around non-performing businesses in an international environment. He has worked in the United Kingdom and the United States, apart from India and Germany. Mr Mathur is on the National Councils of the Confederation of Indian Industry (CII) & Federation of Indian Chambers of Commerce & Industry (FICCI) and is Chairman of the CII Smart Manufacturing Council & past Chairman of CII Western Region. He is also the past President of the Indo-German Chamber of Commerce and the Bombay Chamber of Commerce & Industry."

  },
  {
    image: AshishDhawan,
    title: "Ashish Dhawan",
    desig: "Member, Council of Advisors",
    popupImg:vinayakImg.src,
    popupdesc:"Mr Ashish Dhawan is the Founder-CEO of The Convergence Foundation (TCF), which is focused on accelerating India’s economic growth and development. TCF incubates non-profits focused on creating system-wide impact in the areas of economic growth, equality of opportunity and sustainability. Its current portfolio includes organizations working on jobs and investment, the rule of law, governance and state capacity, economic empowerment of women, science and technology, air pollution, unlocking philanthropic capital, and improving the effectiveness of non-profits. He is also the Founding Chairperson of Ashoka University and Central Square Foundation. Ashoka University was established as a university in 2014 and is already recognized as a leading teaching and research institute across the humanities, social sciences, natural sciences and data & computer science. Central Square Foundation has been a leading voice for foundational literacy and numeracy in India and currently supports several state governments in improving learning outcomes in the early grades. Mr Dhawan also serves on the governing board of the Bill and Melinda Gates Foundation (BMGF). Before his second career as a philanthropist, he was among India’s most successful private equity investors. He founded and ran ChrysCapital, the country’s leading private equity firm. He graduated from Yale University and received his MBA from Harvard Business School."
  },
  {
    image: SNSubrahmanyan,
    title: "S. N. Subrahmanyan",
    desig: "Member, Council of Advisors",
    popupImg:vinayakImg.src,
    popupdesc:"S N Subrahmanyan (SNS) is the Chairman & Managing Director of Larsen & Toubro, a multi-billion-dollar conglomerate. He also holds diverse leadership positions as Chairperson of L&T Finance Holdings Ltd and Chairman of LTIMindtree, L&T Technology Services, and L&T Metro Rail (Hyderabad) Limited. Hailing from Chennai, S N Subrahmanyan embarked on his professional journey with L&T in 1984 as a Project Planning Engineer with a degree in civil engineering from the National Institute of Technology, Kurukshetra and a postgraduate degree in business management from Symbiosis Institute of Business Management, Pune. He furthered his education with an Executive Management Programme from the London Business School. Under his leadership, L&T has been recognised as one of Asia’s Most Honoured Companies by Institutional Investor, the Company of the Year by Business Standard in 2020, among the world's best employers on the Forbes' list and one of India’s Best Employers among Nation-Builders in 2023 by the Great Place to Work (GPTW) institute. SNS won the Eminent Engineer award from the Engineering Council of India in 2024. Apart from being featured on the cover of Fortune magazine’s October 2023 edition as India’s Best CEO, he is also the winner in the Infrastructure & Engineering category of the Business Today-PwC India’s Best CEOs ranking in March 2022, was ranked 8th in the Construction Week Power 100 Ranking for 2022 and was honoured as the Infrastructure Person of the Year in 2012. In 2020, he achieved the Top CEO (Sell Side) and the 3rd Best CEO (Overall) in the All-Asia Executive Team Survey conducted by Institutional Investor and was recognised as the CEO of the Year by the leading Indian news channel, CNBC-Awaaz. His exemplary leadership was also recognised with the Emergent CEO Award in 2019, and he received the Leading Engineering Personality award from the Institution of Engineers (India) in 2014. SNS serves as one of the nine founding members of the Climate Finance Leadership Initiative (CFLI) India, he actively contributes to bringing global scale and influence to this significant initiative. Additionally, he serves as the regular honorary chairperson of the Board of Governors at the National Institute of Technology-Rourkela. In February 2021, he was appointed by the Union Ministry of Labour & Employment as the Chairman of the National Safety Council for two years. Beyond his professional pursuits, SNS embodies a diverse range of interests that reveal the multi-faceted dimensions of his personality. He’s a cricket aficionado and a passionate runner as well. Notably, his appreciation extends beyond sports and fitness, as he also finds solace and passion in the world of Western classical music."
  },

  {
    image: SameerGupta,
    title: "Sameer Gupta",
    desig: "Member, Council of Advisors",
    popupImg:vinayakImg.src,
    popupdesc:"Mr Sameer Gupta is Chairman & Managing Director of Jakson Group – India’s leading Energy & Infra company specializing in Distributed Energy, Solar and EPC solutions. The business interests of Jakson are across multiple lines including Generating Set manufacturing, Solar Module manufacturing, Solar off-grid products, Hybrid Solutions, Battery based Energy Storage Systems, Solar Rooftops, Solar land-based EPC, Electrical EPC in areas of Substation, Transmission & Distribution and Defence solutions. Jakson also has business interests in areas of Civil Infrastructure in India, Real Estate in the UK, and Hospitality. Mr Gupta is currently Chairman of Skill Council of Green Jobs which is a Govt of India initiative. He has served as Chairman of the Confederation of Indian Industry (CII) Northern Region and continues to be actively involved in various Councils & Committees of CII. He is a graduate in Electronics Engineering from Pune University and an alumni of Harvard Business School. His interests include music, travelling and reading books on leadership & spirituality. Mr Gupta’s leadership purpose is to keep learning, invest in people and collaborate to build long enduring relationships on principles of trust and transparency. This is important to him because he cares for people and aspires to take responsibility for creating an institution for both his family and his family business."
  },
  {
    image: DKSen,
    title: "D. K. Sen",
    desig: "Member, Council of Advisors",
    popupImg:vinayakImg.src,
    popupdesc:"Mr. Dip Kishore Sen is a Whole-time Director and Senior Executive Vice President (Development Projects), L&T. He is Chairman on the board of Nabha Power Limited, Power Development Limited, L&T Special Steels & Heavy Forgings Private Limited (LTSSHF), L&T Infrastructure Engineering Company, L&T Oman LLC, L&T Aviation Services Private Limited and Construction Skill Development Council of India (CSDCI). He is a Director on the board of L&T Qatar LLC and Raykal Aluminium Company Private Limited and is also Managing Director for L&T Infrastructure Development Projects Ltd (L&T IDPL). The Minerals & Metals (M&M) Strategic Business Group of L&T comes under his charge. A Civil Engineering graduate from IIT Kharagpur and a Post Graduate in Business Management from XLRI, Jamshedpur, Mr. Sen worked for 12 years with reputed companies like Tata Steel, Jamshedpur and Development Consultants, Kolkata prior to joining L&T. At the beginning of his career, he worked in a turnkey EPC Transmission line project in Malaysia for HGEC, India. He has played a very prominent role in establishing L&T in the GCC Countries by securing several landmark projects and many urban infra-development projects in Qatar, Oman & UAE. He is a member of the curriculum advisory committee of the Post Graduate course in Infrastructure, IIT Kharagpur and the Infrastructure Post Graduate course at Narsee Monjee Institute of Management Studies, Mumbai. He has been associated with various industry organizations like the Federation of Indian Chambers of Commerce & Industry (FICCI), The Confederation of Indian Industry (CII), National Highways Builder’s Federation (NHBF), First Construction Council (FCC) & Construction Federation of India (CFI). He is also the Chairman of the National Council on Roads, Highways & Transportation, ASSOCHAM."
  },

  {
    image: ArunNanda,
    title: "Arun Nanda",
    desig: "Member, Council of Advisors",
    popupImg:vinayakImg.src,
    popupdesc:"Arun Nanda holds a degree in Law from the University of Calcutta, is a fellow member of the Institute of Chartered Accountants of India (FCA) and a fellow member of the Institute of Company Secretaries of India (FCS). Nanda has also participated in a Senior Executive Programme at the London Business School. He joined the Mahindra Group in 1973 and held several important positions over the 40 years he was with the company. He was inducted to the Board of Mahindra & Mahindra Ltd. (M&M) in August 1992 and resigned as Executive Director in March 2010 to focus on the social sector and create a favourable ecosystem for senior citizens. He was a non-executive director from April 2010 till August 2014. He is currently the Chairman of Mahindra Holidays & Resorts (I) Ltd. He is also the Chairman of Holiday Club Resorts Oy, Finland, Chairman of the Governing Board of the Centre for Social and Behaviour Change Communication, Member of the Governing Body of Helpage India and on the Advisory Board of TechnoServe India. He is also Chairman Emeritus of the Indo-French Chamber of Commerce. He was Chairman ofthe  CII Western Region Council for the year 2010-2011, Chairman of the Tourism & Hospitality Skill Council and Chairman of the CII National Task Force on Affirmative Action. He was a Member of the Task Force set up by the B20 on Anti-Corruption which presented the policy paper to President Sarkozy at the G20 Summit held in Cannes in November 2011 and to President Putin in St. Petersburg in June 2013. Nanda is passionate about skilling youth, particularly young girls from backward areas of the country. He was Chairman of the CII National Committee on Skill Development & Livelihood from April 2017 to March 2021 and was on the Board of the National Skill Development Corporation for several years. He is currently a Patron of the PanIIT Alumni Reach For India Foundation (PARFI), an IIT alumnus initiative to skill youth in India, and is the Chairman of PanIIT Alumni Reach For Madhya Pradesh Foundation (PARAM). Nanda was honoured with the 'Chevalier de la Legion d'Honneur' (Knight of the National Order of the Legion of Honour) by the President of the French Republic, Nicolas Sarkozy in 2008."
  },

  {
    image: Arun,
    title: "Arun Maira",
    desig: "Member, Council of Advisors",
    link: "https://www.linkedin.com/in/arun-maira-5499711b4/",
    popupImg:vinayakImg.src,
    popupdesc:"Born on August 15, 1943, in Lahore in undivided India, he has an unusual combination of experience as a hands-on leader, a consultant to leaders, and is widely recognised as a thought leader on subjects like leadership and organisational transformation, in the private, public and social sectors. He has written several books on institutional transformation, and he writes regularly in journals. He was a Member of India's Planning Commission from 2009-14, prior to which he was Chairman of the Boston Consulting Group, India. Earlier, he had worked with the Tata Group in India for 25 years, and for another 10 years with Arthur D Little Inc and Innovation Associates in the USA. Presently, he is Chairman of Helpage International and an advisor to several civil society networks."
  },
  {
    image: DilipCherian,
    title: "Dilip Cherian",
    desig: "Member, Council of Advisors",
    link: "https://www.linkedin.com/in/dilipcherian/",
    popupImg:vinayakImg.src,
    popupdesc:"Dilip Cherian packs in decades of experience and expertise in policy, bureaucracy, economy, and media. His extensive experience as a communications consultant includes advising over 800 corporate CEOs. His expertise in image management and policy affairs is widely recognised. As co-founder of Perfect Relations, the top public relations and public affairs consultancy group in South Asia, Dilip Cherian pioneered the concept of image management in India. Over the course of 32 years, the company, under his leadership, delivered exceptional services to more than 3,800 clients, harnessing 440 professionals in 18 offices across India, His past experiences have been diverse. Dilip Cherian began his career in the government as an Economic Consultant to the Ministry of Industry (B.I.C.P.). He later joined Business India, a prominent publication, and eventually became an editor at one of India's leading business magazines. Along the way he has been an internet start-up founder, run an immensely popular restaurant and launched a TV show. As an independent director, Dilip Cherian serves on the boards of prestigious organizations such as Radio One, one of India's most beloved English Radio FM channels, Jagran, India's largest Hindi daily newspaper, and Bajaj Consumer Care, a leading consumer product giant. Some significant public appointments include positions he’s held on boards like the Advertising Standard Council of India (ASCI), the National Institute of Design (NID), the Apex Committee of Investor Education and Protection Fund (IEPF) under the Ministry of Company Affairs, and the Central Board of Film Certification."
  },
  {
    image: GeetanjaliKirloskar,
    title: "Geetanjali Kirloskar",
    desig: "Member, Council of Advisors",
    link: "https://www.linkedin.com/in/geetanjali-kirloskar-b04203154/",
    popupImg:vinayakImg.src,
    popupdesc:"Chairperson and MD of Kirloskar Systems and Chairperson of Toyota Tsusho Insurance Broker Pvt ltd, Ms Kirloskar is a thought leader and entrepreneur with experience across sectors. She was on the Board of the India Brand Equity Fund of the Commerce Ministry, Co-Chairperson of FICCI India Japan Business Council and Chairperson of the Healthcare CSR Committee of the Government of Karnataka in 2020- 2023, during which she worked to build a modular 100-bed Covid shelter in 45 days. Among many other initiatives, she set up the Sakra World Hospital in a joint venture with Toyota Tsusho and Secom Japan, an insurance brokerage business with Toyota Tsusho, and a joint venture with the Embassy Group for real estate. Honorary Consul Finland at Karnataka, she was awarded a Knighthood from the Finland Government for her exemplary contribution to India-Finland ties. Ms Kirloskar has varied interests. She had her own TV show “Life’s Like That” on Times Now, has acted in two films, has been a speaker at leading forums and writes articles for leading media outlets on business and social issues."
  },
  {
    image: VishalKampani,
    title: "Vishal Kampani",
    desig: "Member, Council of Advisors",
    link: "https://www.linkedin.com/in/vishal-kampani-0a94942a6/",
    popupImg:vinayakImg.src,
    popupdesc:"Vishal Kampani is the non-executive Vice-Chairman of JM Financial Limited, the group’s flagship listed company. He has played a stellar role in transforming the JM Financial group into a financial services powerhouse. He launched the Asset Reconstruction business in 2008 and the Real Estate Finance business in 2009. He joined the JM Financial group in 1997 as an analyst in the Merchant Banking Division and has since moved up the rank and worked across businesses within the group. In a career spanning over 22 years, Kampani has played a key role in consummating several landmark and complex M&A and restructuring transactions. He has been instrumental in expanding the company’s International Operations and building a global profile. In 1999, Kampani worked with Morgan Stanley Dean Witter & Co. in New York, in the Equity Capital Markets Group, where he was involved in structuring creative products for the firm’s clients most of whom were Fortune 500 companies. After returning to India in 2000, he worked as a Senior Banker in the Investment Banking division of JM Morgan Stanley Pvt. Ltd., which was then a joint venture between JM Financial Group and Morgan Stanley. He was, then, responsible for building and maintaining key client relationships, procuring and overseeing the execution of business transactions, advising corporate clients in raising capital, acquisition and divestment of companies, and re-organisation of corporate groups. He was also the head of the corporate finance division. Kampani is a Master of Commerce from the University of Mumbai and has completed his MS (Finance) from London Business School, University of London."
  },
  {
    image: CyrilShroff,
    title: "Cyril Shroff",
    desig: "Member, Council of Advisors",
    link: "https://www.linkedin.com/in/cyrilshroff/",
    popupImg:vinayakImg.src,
    popupdesc:"With over 43 years of experience in a range of areas, including corporate laws, securities markets, banking, infrastructure and others, Mr. Shroff is regarded and has been consistently rated as India's top corporate, banking and project finance lawyer by several international surveys, including those conducted by International Financial Law Review (IFLR), Euromoney, Chambers Global, Asia Legal 500, Asia Law and others. He has won numerous awards from Legal Publications. Mr. Shroff featured in issues of Asian Legal Business (ALB) - Dealmakers of the Year 2016, as the only individual from India. He was also awarded “Emerging Markets Firm Leader of the Year - Independent” at the Asian Lawyer Emerging Markets Awards 2016 organized by American Legal Media. He has been recognized as a “legendary figure in the Indian legal community” and is consistently ranked as “star practitioner” in India by Chambers Global. He is often regarded as the “M&A King of India”. Mr. Shroff is a member of SEBI Committee on Corporate Governance and Insider Trading. He is also a member of the first Apex Advisory Committee of IMC International ADR Centre (IIAC) and an advisory member of the Finance Planning Standard Board of India (FPSB India) and Macquarie. He was recently appointed as a task force member of the Society of Insolvency Practitioners of India (SIPI). He is a member of the Media Legal Defence Initiative (MLDI) International Advisory Board and part of various committees of the Confederation of Indian Industry (CII) and Federation of Indian Chambers of Commerce & Industry (FICCI). He has authored several publications on legal topics. He is a member of the Advisory Board of the Centre for Study of the Legal Profession established by the Harvard Law School, a member of the Advisory Board of the National Institute of Securities Markets (NISM) and on the Board of IIM, Trichy."
  },

  {
    image: khurshed,
    title: "Khurshed",
    desig: "Member, Council of Advisors",
    link: "https://www.linkedin.com/in/khurshed-daruvala/",
    popupImg:vinayakImg.src,
    popupdesc:"Khurshed Daruvala, Chairman of Sterling and Wilson Group (S&W), is a visionary, whose contribution to steering the company’s growth and expansion underlines a perfect blend between cherished traditions and a contemporary business approach. The catalyst behind the company’s evolution into a global powerhouse of businesses across verticals, Khurshed has led from the front since he joined Sterling and Wilson in 1997. He is credited with powering S&W’s emergence as India’s leading MEP (Mechanical, Electrical and Public Health Engineering) and Renewable Energy solutions provider. Khurshed has been instrumental in introducing Solar EPC way back in 2011, a segment he believed had great growth potential. This decision changed the face of S&W and accelerated the company’s growth. A Chartered Accountant by qualification, he has made Sterling and Wilson one of India’s leading companies in the EPC sector. Today, S&W is a name to reckon in the global arena. He has spent the past two decades building a fast-growing business empire – taking the company’s turnover from a meagre 1mn USD in 1997 to ~1bn for the year ending 2021 and expanding the team from fewer than 100 to ~4000 highly talented people. Under his leadership, S&W has diversified in several emerging segments such as Turnkey Data Centers, Transmission & Distribution, Diesel Generators and E- Mobility, and established a footprint in over 30 countries spread across India, the Middle East, Africa, Southeast Asia, Australia, Europe and the Americas. Mr. Daruvala holds a bachelor’s degree in commerce from the University of Mumbai and is an Associate Member of the Institute of Chartered Accountants of India (ICAI). He has been part of the Sterling and Wilson Group for almost 28 years. He has been on the board of Sterling and Wilson Renewable Energy Limited since April 25, 2018.	"
  },
];

export const fellow = [
  {
    image: rasikaAthawale,
    title: "Rasika Athawale",
    desig: "Distinguished Fellow (Power)",
     popupImg:vinayakImg.src,
    link: "https://www.linkedin.com/in/rasika-athawale-5072ab1/",
    popupdesc:"Rasika is a management professional with around two decades of experience in energy & utilities sector, working as a power utility executive, strategy consultant with Big4 management consulting firms, research program manager at a Big Ten U.S. State University and a U.S. Think Tank. Her research expertise includes economics of the power sector and energy transition, government policy and regulatory impact analysis, planning and strategy formulation for utilities, and financial modelling with publication in leading academic journals and print news media. She has a strong track record of executing complex consulting engagements and managing client relationships with federal and state governments in India and the United States. She has the proven ability to conceptualize, market and execute project work as an individual consultant with experience in managing thought leadership charters for expert advisors and a leading energy efficiency analytics firm. She is a thought leader and sector influencer in promoting inclusive dialogue by simplifying complex information under the brand of “India Energy Insights”. She writes and provides inputs for media outlets (contributing author for MoneyControl), has published “Electric utility death spiral: Revisited in the context of tariff design” in The Electricity Journal, December 2021 which features in the list of most downloaded articles, and has been a speaker at the Virtual Workshop on Regulatory Reforms, organized by the National Institute of Advanced Studies, April 2022. A B.Tech in Chemical Engineering (Nagpur University) and a PGDBM (Finance) from Sydenham Institute of Management, Mumbai University, Rasika’s career has spanned a slew of well-known organisations (and high-profile projects in the energy sector) including Adani Electricity, ICICI Bank, PricewaterhouseCoopers, KPMG Advisory Services, APPRISE Incorporated Princeton (USA), Rutgers NJ, Hiranandani Group, and several others. She has been a Faculty for Distribution Reforms training programme by USAID (2004-2005), and a Member, National Team, India Smart Grid Forum and Member, Maharashtra State Smart Grid Committee (to determine measures for strengthening of R-APDRP by the Ministry of Power, Delhi) in 2011-2012."
  },

  {
    image: supratimSarkar,
    title: "Supratim Sarkar",
    desig: "Distinguished Fellow (Financial Services)",
     popupImg:vinayakImg.src,
    popupdesc:"Mr Supratim Sarkar has over 25 years of experience in the field of financial services. Having joined IDBI in 1995, and thereafter moved to SBICAPS in November 2000, he has worked as Executive Vice President and Group Head at SBICAPS for 12 years, heading a team of about 300 professionals working in the area of Project Finance, Corporate Finance, Structured Finance, Advisory areas for projects bidding, auctions of mines, disinvestments, etc. Since March 2022, he has been pursuing an independent career, working on multiple projects as a Financial Advisor. He has a strong network with leaders in the private sector, in PSUs and banks, with Chief Investment Officers of Funds, senior bureaucrats and Government Departments. He has worked on different committees set up by state Governments and the Government of India, on matters such as reintroduction of DFI, resolution of Coastal power projects based on imported coal, resolution of tariff for IPPs, etc. He had also been associated with the resolution of stalled and/or stressed projects. He led the ideation of the National Bad Bank currently christened as NARCIL. He was a part of the CII Infrastructure sub-committee and of the FICCI delegations to the US and Canada along with Government dignitaries. He has been a regular speaker at different webinars and panel discussions organised by the industry chambers or industry partners. After graduating as a Mechanical Engineer from Jadavpur University in 1988, Mr Sarkar completed his post-graduation in Aeronautical Engineering from IIT Madras and thereafter completed his MBA with specialisation in Finance from BIM Tiruchirapalli."
  },
  {
    image: rajivRanjanMishra,
    title: "Rajiv Ranjan Mishra",
     popupImg:vinayakImg.src,
    desig: "Distinguished Fellow (Water Conservation)",
    popupdesc:"Mr Rajaji Meshram has over 25 years of experience in Strategy Development, Business Planning and development of Regulatory Frameworks in several large infrastructure projects in India as well as countries such as Bangladesh, Saudi Arabia, Mongolia, Kenya, UAE and Sri Lanka. He started his career with the Indian Railways where he spent more than 6 years working across different areas of operations, maintenance, and project management. He has been a part of various Policy formulation, Feasibility assessment, Transaction Advisory and Public Private Partnership (PPP) projects across sectors in the transportation domain. His last corporate role was Partner, EY India. He has worked in leading corporates like IBM, KPMG and PWC. He is currently working on projects with the World Bank and Asian Development Bank as an independent expert. Some of his notable works include: preparation of LEADS report, Ministry of Commerce and Industry, Government of India; updating the National Transport Policy 2006 of Bhutan for the United Nations Development Programme; Logistics Capacity Development in Mongolia, Asian Development Bank; assessment of cost reduction opportunities for Saudi Arabia Railway; process audit of Etihad Rail DB, UAE; providing advisory services for structuring of track access charges (tariffs) and setting a non-discriminatory access regime in Dedicated Freight Corridor Corporation of India Ltd. (DFCCIL) (World bank funded project); developing a Regulatory Structure for the Visakhapatnam Chennai Industrial Corridor, Andhra Pradesh for Asian Development Bank; recommending a corporate planning framework for Railway Planning & Investment Organization (RPIO) and Special Unit for Transportation Research and Analysis (SUTRA) in Indian Railways; Sagarmala Project Management consultancy for Ministry of Shipping and Ports, Government of India; Transaction Advisory for Concession and Operation Agreements for creating Open Access Aviation Fuel Facility at Airports for Airports Authority of India; capacity development in Oxygen Logistics in four states and assisting in developing tools for oxygen transport planning through road and rail, World Bank. Rajaji has an MBA from IIM Ahmedabad and has been a part of the prestigious Gurukul Leadership program at the London School of Economics. He is a member of the National Council of The Chartered Institute of Logistics and Transport, India."
  },
  {
    image: rajajiMeshram,
    title: "Rajaji Meshram",
     popupImg:vinayakImg.src,
    desig: "Distinguished Fellow(Transport & Logistics)",
    link: "https://www.linkedin.com/in/rajaji-meshram-9aa3437/",
    popupdesc:"Rajiv Ranjan Mishra recently retired from his position as Director General for the National Mission for Clean Ganga (NMCG), during which he transformed the Namami Gange programme into an integrated, multi-sectoral model framework for river rejuvenation in India. As Additional Secretary for India’s Ministry of Housing and Urban Affairs, he steered several policies in the housing sector, urban SDGs, New Urban Agenda and sustainable technologies, and played a pivotal role in the enactment of the landmark Real Estate (Regulation & Development) Act, 2016-RERA. In 2021, Mr. Mishra was bestowed with the Annual Research Award from IIT Roorkee for his work on the rejuvenation of the river Ganga. Over the course of his time at NMCG, he led the organisation to international and national recognition including the Public Agency of the Year Award (Distinction) by Global Water Intelligence. Mr. Mishra introduced a paradigm shift at NMCG through several key projects and policy interventions, including PPPs in wastewater management through a hybrid annuity mode and a ‘One City-One Operator’ approach for better sustainability and governance in wastewater management. Mr. Mishra has also developed pioneering frameworks to plan ‘river cities’ by mainstreaming rivers and water within urban master plans, highlighting water-sensitive urban design and developing the River City Alliance. Mr. Mishra is the co-author of ‘Ganga: Reimagining, Rejuvenating, Reconnecting’, a change-maker’s account of the enormity of the challenges, institutional processes and reforms which developed momentum and positively impacted a river’s health and the sustainability of those impacts. He has published several articles, papers and opinion columns in several journals, and magazines, as well as editing a special issue on river rejuvenation in the Journal of Governance and working as editor and contributor on ‘Managing Urban Rivers: from Planning to Practice’, a set of articles by national and international experts being published by Elsevier. He has contributed to many national and international trainings and seminars, and holds Certificates in Advanced Studies in Public Administration from Maxwell School, Syracuse University, USA; Public Budgeting from Georgia State University, Atlanta; Project Management from University of California, Berkeley; and the ‘Leaders in Development’ programme from Harvard Kennedy School, Cambridge, USA. He is Chief Advisor and Chairman of Strategy & Policy Unit at the National Institute of Urban Affairs in India, and additionally acts as an advisor for the Centre for Ganga River Basin Management and Studies at the Indian Institute of Technology (IIT) in Kanpur."
  },

  {
    image: SoumyaKantiGhosh,
    title: "Soumya Kanti Ghosh",
    desig: "Distinguished Fellow (Economic Policy)",
     popupImg:vinayakImg.src,
    link: "https://www.linkedin.com/in/soumya-kanti-ghosh-2043921a/",
    popupdesc:"Soumya Kanti Ghosh is currently the Group Chief Economic Advisor, the State Bank of India. Previously, he has worked at Tata AIA, American Express and ICRA among others. Dr Ghosh has been a co-author in pioneering work to capture payroll data in India for the first time, both formal and informal, contributing to the design of the PMKISAN scheme for farmers, the ECLG scheme for MSME borrowers, restructuring of the CGTSME scheme among others that have been very successful during the times of pandemic and post-pandemic. Following his report, EPFO and ESIC have started to give out monthly payroll data. He serves as a Chairman of the Indian Banks’ Association’s Economist Group. He is also a member of the Insolvency Board Committee on Research, and the Editorial Advisory Board of the Indian Institute of Banking and Finance. Dr Ghosh is also a member of the Governing Board at the Indian Institute of Corporate Affairs. For 6 successive years ending 2023, Dr. Ghosh has been ranked as one of the Best Individuals in Research in India by the Asset magazine. Dr Ghosh has an extensive list of publications in media, and international and national journals. Dr Ghosh has completed his doctoral thesis from Jawaharlal Nehru University (JNU)."
  },
  {
    image: AkhileshTilotia,
    title: "Akhilesh Tilotia",
    desig: "Distinguished Fellow (Public Policy)",
    link: "https://www.linkedin.com/in/atilotia/",
     popupImg:vinayakImg.src,
    popupdesc:"Akhilesh Tilotia is a keen observer of the economic, political, and social landscape of India. His unique perspective in commentary is shaped by his varied experiences as a government officer, an economist, a banker, and a strategist. These multiple world-views have enabled him to emerge as a “dot-joiner” – piecing together disparate issues into a coherent picture. In his previous roles, he has served as the Head of Research at the National Investment and Infrastructure Fund. He has led Strategy and New Initiatives for Axis Bank, worked with the Kotak Group, The Boston Consulting Group, and was a co-founder of PARK Financial Advisors. His best-selling book, The Making of India – Game-Changing Transitions (2015), introduced the concept of 'private cost of public failure' and explored how it opened up opportunities for investors. His second book, Through the Looking Glass (2021), examines the India story from the perspectives of bureaucrats, politicians, and citizens drawn from his close observations during a three-year stint in New Delhi with a Union Minister. Akhilesh holds an MBA from IIM Ahmedabad and is an MITx alumni, in addition to certifications from CFP and CFA. He is a prolific columnist and commentator in the business media having written numerous reports and briefing papers on varied topics. His current focus is on the intersection of climate, finance, and policy. He is passionate about astronomy, mythology, and chasing curiosities."
  },
];

export const team = [
  {
    image: Vinayak,
    title: "Vinayak Chatterjee",
    desig: "Founder & Managing Trustee",
     popupImg:vinayakImg.src,
    popupdesc:"Born in 1959, Vinayak Chatterjee graduated in Economics (Hons) from St. Stephen's College, Delhi University (1976-1979) and did his MBA from the Indian Institute of Management, Ahmedabad (1979 – 1981). He co-founded Feedback Infra Pvt. Ltd. in 1990 and served as its Chairman from 1990 to 2021. Since stepping down from active management, he now devotes his time and energy to Infrastructure Policy and Advocacy; as well as to nurturing educational institutions. He has often been called upon to play a strategic advisory role to leading domestic and international corporates, the Government of India, various Ministries dealing with infrastructure, as well as multilateral and bilateral institutions in the areas of infrastructure policy, planning and implementation. He is one of the leading proponents of the Public-Private Partnership (PPP) model for developing India’s infrastructure. His more recent engagements with the Government of India relate to being a Member of the Committee on Setting up a DFI (Development Finance Institution), and a member of the Consultative Group on PPPs at NITI Aayog. In 1998, the World Economic Forum at Davos recognized him as one of the 100 Global Leaders of Tomorrow. In 2011, the Indian Institute of Management, Ahmedabad conferred on him the “Distinguished Alumnus Award”. He is currently the Chairman of the Confederation of Indian Industry’s (CII) “National Council on Infrastructure”; and he has chaired various Infrastructure and Economic Committees at the national level of CII since 2001. He is on the Board of Directors of ACC Limited, Apollo Hospitals Enterprise Limited, KEC International Limited, and L&T Infotech Limited; and is a member of the Advisory Board of JCB India. He serves as the Chairman of the Board of Governors of the Indian Institute of Technology, Dharwad, and on the Boards of the Indian Institute of Management, Sirmaur and the National Rail and Transportation Institute, Vadodara. He is a well-read columnist and writes a monthly column on infrastructure for Business Standard called ‘INFRATALK’. He has authored a book titled “Getting it Right – India’s Unfolding Infrastructure Agenda” published in 2011. He lives in Gurugram, in the National Capital Region of India."
  },
  {
    image: RumjhumChatterjee,
    title: "Rumjhum Chatterjee",
    desig: "Co-Founder & Managing Trustee",
     popupImg:vinayakImg.src,
    popupdesc:"Rumjhum Chatterjee - one of the co-founders of Feedback Infra Group, has recently stepped out of an operational role within the Group. Before her retirement, she served as the Group Managing Director and Head – Human Capital. She is the Chairperson of the Feedback Foundation Charitable Trust. The Trust is deeply involved in rural and urban sanitation issues, including solid waste management, and has successfully implemented several projects across the country through community engagement. Rumjhum pioneered the practice of community-led interventions for R&R post-land acquisition for infrastructure projects. Her paper on ‘Sustainable Rehabilitation Interventions through Community Engagement’ was published in the India Infrastructure Report 2009, published by 3iNetwork. A leading practitioner of the management of human capital in the infrastructure sector, she was recognized as one of the 20 Most Talented HR Leaders in India by the World HRD Congress in 2013. She plays an active role in the Confederation of Indian Industry (CII) and served as the first woman Chairperson for the CII Northern Regional Council (2016-17). She has a deep interest in women’s empowerment. She served as Chairperson of CII’s Women Exemplar Program 2015-17 and has been part of the Jury of the Selection Committee of the same program since its inception in 2005. She also served as the Chair of the CII National Women’s Empowerment Committee for several years. Rumjhum has represented the industry’s views on women’s empowerment before Parliamentarians in India. She also participated in a closed-door interaction to discuss the same with the Prime Minister of Japan, Mr. Shinzo Abe, during his visit to India in January 2014. Currently, she is the Co-Chair of CII’s National Committee on CSR. She has served as an Independent Director on the Board of Blue Star Limited and currently serves on the Board of Somany Ceramics Limited and C&S Electric Ltd. (a subsidiary of Siemens India Ltd.). She is the Vice Chairperson and a member of the Governing Body of HelpAge India – India’s largest not-for-profit organisation dedicated to the welfare of the aged. She is also a Trustee of HDFC Schools. Rumjhum is educated in Psychology from Calcutta University."
  },
  {
    image: jagan,
    title: "Jagan Shah",
    desig: "CEO",
    link: "https://www.linkedin.com/in/jagan-shah/",
     popupImg:vinayakImg.src,
    popupdesc:"Jagan Shah is an architect and urbanist with a deep interest in the future of cities. Currently a Senior Expert in urban development policy and practice at Artha Global, he has been engaged with the urban sector in India for over twenty years, through consultancy, teaching, writing and public speaking. From 2013 till 2019, he was Director of the National Institute of Urban Affairs, India’s premier urban think tank. Under his leadership, the organisation provided evidence-based policy and planning support to urban local bodies, state governments and the central Ministry of Housing & Urban Affairs for a diverse range of subjects including smart city development, e-governance, integrated spatial & physical planning, water & sanitation, municipal finance, transit-oriented development, land value capture, resilience and sustainability. He is a member, the Board of Trustees, Clean Air Asia India. He has also been a consultant with the World Bank and a Resident Senior Fellow at IDFC Institute. He received his education and training at the School of Planning & Architecture, New Delhi, the University of Cincinnati and Columbia University, New York."
  },
  {
    image: KavereeBamzai,
    title: "Kaveree Bamzai",
    desig: "Head Advocacy",
    link: "https://www.linkedin.com/in/kavereebamzai/",
     popupImg:vinayakImg.src,
    popupdesc:"Kaveree Bamzai has been a journalist for 35 years. She was the first and so far only woman editor of India Today magazine, where she worked for 17 years, before leaving in 2019 to pursue an independent career. She has worked in various capacities with two major national dailies, The Times of India and The Indian Express, handling diverse portfolios, from front page editor to Sunday Magazine editor. At India Today she edited special issues dedicated to key areas of development, from infrastructure to social entrepreneurship. She also curated the annual India Today Conclave, a meeting ground for thought leaders and opinion makers; started Mind Rocks, an annual event for young people, as well as the India Today Woman Annual Summit and Awards. She also curated the annual Safaigiri Awards and Summit after the announcement of the Swachh Bharat Mission. Since leaving India Today, she has curated events for The New Indian Express and ABP Network, including a national education conclave, ThinkEdu; the annual Odisha Literary Festival; the Devi Awards for Women; and the Ideas of India Summit. She is a frequent speaker at media and literary events and has been a TEDx speaker as well. She is the author of several monographs and essays, as well as three books, among them No Regrets: The Guilt-free Woman's Guide to a Good Life and The Three Khans and the Emergence of New India. She is a frequent columnist on cinema and society for Dainik Bhaskar, The Times of India Plus, and The New Indian Express, and is a contributing editor to Open magazine. She is the presenter of Tiffin Talks, a popular series of digital interviews with media personalities, as well as street stories, dedicated to women who are making a difference. She went to school at the Convent of Jesus and Mary, New Delhi, Loreto and La Martiniere Kolkata. She did an undergraduate degree in economics at St Xavier's College, Kolkata, and did a postgraduate degree in sociology at the Delhi School of Economics where she won the MSA Rao Scholarship for Academic Excellence. She was also a Chevening Fellow, a scholarship awarded by the British Foreign and Commonwealth Office. She was designated a game-changer by Save the Children charity, is a member of the Women Exemplar Jury of the CII Foundation, and has been a member of several juries and committees in the media space. She lives in Delhi with her husband, two boys and a perennially hungry Labrador. - Policy Advisory for policy-makers - Transaction support with market & commercial due diligence for global investors - Transaction for bid advisory for both the public and private sector - Investment options and feasibility analysis - Sectoral Strategy."
  },
  {
    image: MutumChaobisana,
    title: "Dr. Mutum Chaobisana",
    desig: "Head Programmes",
     popupImg:vinayakImg.src,
    link: "https://www.linkedin.com/in/dr-mutum-chaobisana-83647017/",
    popupdesc:"Dr. Mutum Chaobisana is an Architect-Urban Planner with a PhD in Urban Planning and a distinguished career marked by significant contributions to the urban sector and the development of Himalayan ecosystems in India. Her roles have included Head-Programmes at The Infravision Foundation, Lead-Urban Planner at IIFCL Projects Ltd. (a PSU under the Ministry of Finance), Sector Coordinator-Urban Planning at the National Institute of Urban Affairs (NIUA), Senior Consultant at the Ministry of Housing and Urban Affairs, and Assistant Director (Planning) at the Delhi Development Authority. In these positions, she has played crucial roles in policy formulation, drafting development control norms and implementation of infrastructure projects. She has delivered innovative and sustainable rural-urban solutions, shaped strategic projects, and formulated vision and strategies for urban development. She has successfully spearheaded master plans, including the Delhi Master Plan 2021 and 2041, Slum Rehabilitation Policy, developed national policy and guidelines in urban flagship missions like PMAY-U, Rental Housing, Retirement Homes as well as worked on eco-tourism, conservation of natural ecosystems and riverfront development, townships and regional planning initiatives in Northeast Region. Throughout her professional tenure, Dr. Mutum has been affiliated with esteemed entities such as the Ministry of Finance, the Ministry of Tourism, the Ministry of Housing and Urban Affairs, State Government agencies, the Ministry of Development of Northeastern Region, and various international donor agencies. Her proficiency in stakeholder engagement and fostering strategic partnerships has been instrumental in driving inclusive growth and sustainable development. She is adept at fostering collaborative relationships with State and Central Government agencies, donor agencies, and efficiently delivering vision and strategic development initiatives and infrastructure projects. She is well-versed in coordinating and managing partnerships with international agencies, think tanks, government officials at State and Central Ministries, Urban Local Bodies (ULBs), political leaders, civil societies, and NGOs."
  },

  {
    image: VrindaSingh,
    title: "Vrinda Singh",
    desig: "Research Associate",
    link: "https://www.linkedin.com/in/vrinda-singh-3951951b4/",
     popupImg:vinayakImg.src,
    popupdesc:"Vrinda Singh is a dynamic urban policy enthusiast with a passion for shaping the future of India's cities. In her role as a Research Associate at The Infravision Foundation (TIF), she channels her enthusiasm for urban development into impactful initiatives. Vrinda Singh's educational journey exemplifies her dedication to unravelling the complexities of urban development. Armed with a dual master's degree—one in Political Science from Calcutta University and another in Public Policy and Governance from Tata Institute of Social Sciences (TISS), specializing in Urbanisation—she embodies a profound commitment to understanding and addressing the nuances of urban policy. Her diverse experiences, spanning across esteemed organizations like The Energy and Resources Institute (TERI) and Janaagraha, have equipped her with comprehensive knowledge and hands-on experience in climate action plans, flood management policies, civic engagement initiatives, urban governance complexities, parliamentary research and green transport research, demonstrating her expertise in conducting primary and secondary research, analyzing policies, interpreting data, and engaging with stakeholders. In addition to her professional pursuits, Vrinda holds a profound interest in infrastructure planning, finance, and sustainable development, with a distinctive focus on addressing climate change and environmental sustainability. She is deeply committed to advocating for policies and initiatives that promote environmental stewardship and resilience, embodying an unwavering dedication to catalysing positive change in the realm of public policy. As she continues her journey at TIF, Vrinda remains dedicated to driving positive change in India's urban landscape, fostering sustainable development through her innovative initiatives."
  },
  {
    image: LawrenceCardoza,
    title: "Lawrence Cardoza",
    desig: "Research Associate",
    link: "https://www.linkedin.com/in/lawrence-cardoza/",
     popupImg:vinayakImg.src,
    popupdesc:"Lawrence Cardoza is a passionate advocate for sustainable development and a proponent of data-backed policymaking to bring about real impact for those who need it the most. As a Research Associate at The Infravision Foundation (TIF), he aspires to build compelling narratives to put the “public” back in public policy and strengthen the foundations of a resilient nation by further developing infrastructure policies. Holding a PGP in Public Policy, Design, and Management from the Indian School of Public Policy and a B.A. from St. Stephen's College, Lawrence combines academic rigour with hands-on experience. He has previously worked across diverse industries and functions, including operations at Better.com, sales and outreach at GenElek Technologies (working with paraplegic veterans), and communications at the Delhi Lawn Tennis Association, where he developed strong expertise in stakeholder management, data analysis, and strategic communication. At TIF, Lawrence contributes to policy analysis, research projects, and assists in organizing initiatives like the 'InfraKatha' sessions, aimed at fostering informed discussions on the future of infrastructure in India. With a keen interest in social infrastructure and climate-resilient infrastructure and its intersection with public welfare, Lawrence excels at translating complex policy issues into accessible formats to engage broader audiences. His background also includes a focus on public policy evaluation and the socio-economic impact of initiatives, highlighted by his previous internship at the National Investment & Infrastructure Fund. A certified mountaineer, he completed his Basic Mountaineering Course from the Nehru Institute of Mountaineering, and in his free time, he enjoys reading, callisthenics, and long-distance cycling."
  },
  {
    image: PriyankaBains,
    title: "Priyanka Bains",
    desig: "Research Associate",
     popupImg:vinayakImg.src,
    link: "https://www.linkedin.com/in/priyanka-bains-b070607b/",
    popupdesc:"Priyanka Bains is an economist by training and a problem-solver at heart. She graduated from Lady Shri Ram College for Women with a degree in Economics and pursued her Master’s in economics at Jawaharlal Nehru University. Passionate about development, policy, and sustainability, she’s on a mission to make agriculture smarter, more efficient, and climate-resilient—because feeding the world shouldn’t cost the planet. With a keen interest in climate resilience, sustainable infrastructure, and data-driven policymaking, Priyanka thrives on exploring innovative solutions that balance economic growth with environmental responsibility. When she’s not working, she enjoys unwinding with a good book and a freshly brewed cup of coffee, always eager to learn something new."
  },
];
