


import "./globals.css";
import type { Metadata } from "next";
import Footer from "@/_components/organism/footer";
import Header from "@/_components/organism/header";
import { HeaderProvider } from "@/context/useHeader";

export const metadata: Metadata = {
  title: "The Infravision Foundation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased `}>
        <HeaderProvider>

          <Header />
          {children}
          <Footer />
        </HeaderProvider>
      </body>
    </html>
  );
}
