import type { Metadata } from "next";

import "./globals.css";
import Footer from '@/_components/organism/footer'
import Header from "@/_components/organism/header";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
